/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package inventorysystem;


import inventorysystem.Beans.Invoice;
import inventorysystem.Beans.InvoiceItem;
import inventorysystem.Beans.Item;
import inventorysystem.DB.DBType;
import inventorysystem.DB.DBUtil;
import inventorysystem.Tables.InvoiceItemTable;
import inventorysystem.Tables.InvoiceTable;
import inventorysystem.Tables.ItemTable;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.ComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.JTextComponent;

/**
 *
 * @author HP
 */
public class AddInvoice extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddInvoice
     */
    AddCompaney ac;
    AddItem addItem;
    public InvoiceItem i = new InvoiceItem();
    private static final String COMMIT_ACTION = "commit";
    public AddInvoice() {
        initComponents();
        
        itemNameCmbx.setEditable(false);
        quantityTxb.setEditable(false);
        newInvoiceBtn.setEnabled(false);
        addItemBtn.setEnabled(false);
        addBtn.setEnabled(false);
        itemNameCmbx.setFocusTraversalKeysEnabled(true);
        
        
        String sql = "SELECT * FROM company";
        try (
        Connection conn = DBUtil.getConnection(DBType.MYSQL);
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
    ){
            if(companyCmbx.getItemCount()!=0)
             companyCmbx.removeAllItems();
            while(rs.next())
            {
                companyCmbx.addItem(rs.getString("name"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddToVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        /////////////////////////////////////////////////////////////////////Search item 
       itemNameCmbx.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
          @Override
          public void keyReleased(KeyEvent evt){
              String str = itemNameCmbx.getEditor().getItem().toString();
              if(evt.getKeyCode()>=65 && evt.getKeyCode()<=90 || evt.getKeyCode()>=96 && evt.getKeyCode() <= 105 || evt.getKeyCode() == 8)
               {
                  try {
                      itemNameCmbx.setModel(ItemTable.getList(str));
                      if(itemNameCmbx.getItemCount()>0){
                         itemNameCmbx.showPopup();
                         if(evt.getKeyCode()!=8){
                             ((JTextComponent)itemNameCmbx.getEditor().getEditorComponent()).select(str.length(), itemNameCmbx.getEditor().getItem().toString().length());
                         }else{
                             itemNameCmbx.getEditor().setItem(str);
                         }
                      }else{
                          itemNameCmbx.getEditor().setItem(str);
                      }
                  } catch (SQLException ex) {
                      Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
                  }
               }
           }
       });
       
       
       /////////////////////////////////////////////////////////////
       
      //////////////////////////////////////////////////////////////
     
       /////////////////////////////////////////////////////////////////////////////
       
       ////////////////////////////////////////////////////////////////////////////
       //////////////////////////////////////////////////////////////
      
       
       /////////////////////////////////////////////////////////////////////////////
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        containsMatcher1 = new ch.rakudave.suggest.matcher.ContainsMatcher();
        jScrollPane2 = new javax.swing.JScrollPane();
        invoiceTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        addItemBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        quantityTxb = new javax.swing.JTextField();
        itemNameCmbx = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        invoiceNoTxb = new javax.swing.JTextField();
        addCompanyBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dateDtp = new datechooser.beans.DateChooserCombo();
        jLabel6 = new javax.swing.JLabel();
        createInvoiceBtn = new javax.swing.JButton();
        newInvoiceBtn = new javax.swing.JButton();
        companyCmbx = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        totalAmountTxb = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add an Invoice");

        invoiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Invoice No", "Item Name", "No of box", "Agent Price", "Total Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(invoiceTable);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel5.setText("Add Invoice");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton5.setText("Pay");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jButton6.setText("Exit");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        addBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel2.setText("Item Name");

        addItemBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        addItemBtn.setText("+");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Quantity(Boxes)");

        quantityTxb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        quantityTxb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxbActionPerformed(evt);
            }
        });

        itemNameCmbx.setEditable(true);
        itemNameCmbx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemNameCmbxMouseClicked(evt);
            }
        });
        itemNameCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameCmbxActionPerformed(evt);
            }
        });
        itemNameCmbx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                itemNameCmbxKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemNameCmbxKeyReleased(evt);
            }
        });

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(quantityTxb, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(itemNameCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(addItemBtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemNameCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quantityTxb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        invoiceNoTxb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        addCompanyBtn.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        addCompanyBtn.setText("+");
        addCompanyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCompanyBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel1.setText("Invoice No:");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel3.setText("Company");

        dateDtp.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
        dateDtp.setFormat(2);

        jLabel6.setText("Date");

        createInvoiceBtn.setText("Create Invoice");
        createInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createInvoiceBtnActionPerformed(evt);
            }
        });

        newInvoiceBtn.setText("New Invoice");
        newInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newInvoiceBtnActionPerformed(evt);
            }
        });

        companyCmbx.setEditable(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(invoiceNoTxb)
                            .addComponent(dateDtp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(companyCmbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCompanyBtn)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(newInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(createInvoiceBtn)
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(invoiceNoTxb, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addCompanyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateDtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createInvoiceBtn)
                    .addComponent(newInvoiceBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        totalAmountTxb.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        totalAmountTxb.setText("0");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setText("Total Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)
                        .addGap(28, 28, 28)
                        .addComponent(totalAmountTxb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(354, 354, 354))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(18, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(totalAmountTxb))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
                
        try {
            // get Item detils
            InvoiceItem invoiceItem = InvoiceItemTable.getLastRow(itemNameCmbx.getSelectedItem().toString(), companyCmbx.getSelectedItem().toString());
            i = new InvoiceItem();
            if(InvoiceItemTable.isCompareItems(itemNameCmbx.getSelectedItem().toString(), companyCmbx.getSelectedItem().toString()))
            {
                i.setStockId(invoiceItem.getStockId());
            }else{
                i.setStockId(invoiceItem.getStockId()+1);
            }
            
            i.setInvoiceNo(InputHelper.getIntegerInput(invoiceNoTxb.getText()));
            i.setItemName(itemNameCmbx.getSelectedItem().toString());
            i.setNoOfBox(InputHelper.getIntegerInput(quantityTxb.getText()));
            i.setRemainingCapacity(InputHelper.getIntegerInput(quantityTxb.getText()));
            i.setCompanyName(companyCmbx.getSelectedItem().toString());

            Item item = ItemTable.getRow(i.getItemName());// get the item record
            //item.setCurrentStock( (item.getCurrentStock()+InputHelper.getIntegerInput(quantityTxb.getText())));
            i.setAgentPrice_pack(item.getAgentPrice_pack());
            i.setWsPrice_pack(item.getWsPrice_pack());
            i.setRtailPrice_pack(item.getRetailPrice_pack());
            i.setTotal(i.getNoOfBox()*i.getAgentPrice_pack());
            
           
                if(InvoiceItemTable.insert(i)){
                   
                    totalAmountTxb.setText(Float.toString(InvoiceItemTable.getBill(InputHelper.getIntegerInput(invoiceNoTxb.getText()))));
                    
                    invoiceTable.setModel(InvoiceItemTable.getInvoiceDetailsToTable(InputHelper.getIntegerInput(invoiceNoTxb.getText())));
                }
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
       
        
    }//GEN-LAST:event_addBtnActionPerformed

    private void addCompanyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCompanyBtnActionPerformed
        // TODO add your handling code here:
        if ( ac!=null){
            ac.dispose();
        }
        ac = new AddCompaney();
        ac.setVisible(true);
        ac.setAlwaysOnTop(true);
    }//GEN-LAST:event_addCompanyBtnActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        // TODO add your handling code here:
        if(addItem!=null){
            addItem.dispose();
        }
        addItem = new AddItem();
        addItem.setVisible(true);
        addItem.setAlwaysOnTop(true);
    }//GEN-LAST:event_addItemBtnActionPerformed

    private void createInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createInvoiceBtnActionPerformed
        // TODO add your handling code here:
        Invoice i = new Invoice();
        i.setInvoiceNo(InputHelper.getIntegerInput(invoiceNoTxb.getText()));
        i.setDate(InputHelper.getValidFormatedDate(dateDtp.getText()));
        i.setCompanyName(companyCmbx.getSelectedItem().toString());
        try {
           if(InvoiceTable.insert(i)){
               // disable
               invoiceNoTxb.setEditable(false);
               companyCmbx.setEditable(false);
               dateDtp.setEnabled(false);
               createInvoiceBtn.setEnabled(false);
               addCompanyBtn.setEnabled(false);
               
               // enable
             newInvoiceBtn.setEnabled(true);
             itemNameCmbx.setEditable(true);
             quantityTxb.setEditable(true);
             addItemBtn.setEnabled(true);
             addBtn.setEnabled(true);
           }
           
           
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Can't insert data", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_createInvoiceBtnActionPerformed

    private void newInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newInvoiceBtnActionPerformed
        // TODO add your handling code here:
        
        // clear text boxes
        invoiceNoTxb.setText("");
        companyCmbx.removeAllItems();
        itemNameCmbx.removeAllItems();
        quantityTxb.setText("");
        invoiceTable.setModel(new DefaultTableModel());
       
        //disable
        itemNameCmbx.setEditable(false);
        quantityTxb.setEditable(false);
        newInvoiceBtn.setEnabled(false);
        addItemBtn.setEnabled(false);
        addBtn.setEnabled(false);
       
        // enable
       invoiceNoTxb.setEditable(true);
       companyCmbx.setEditable(true);
       dateDtp.setEnabled(true);
       createInvoiceBtn.setEnabled(true);
       addCompanyBtn.setEnabled(true);
       
       
       
       String sql = "SELECT * FROM company";
        try (
        Connection conn = DBUtil.getConnection(DBType.MYSQL);
        Statement stmt = conn.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
    ){
            if(companyCmbx.getItemCount()!=0)
             companyCmbx.removeAllItems();
            while(rs.next())
            {
                companyCmbx.addItem(rs.getString("name"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddToVehicle.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
       
    }//GEN-LAST:event_newInvoiceBtnActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void quantityTxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxbActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_quantityTxbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String invoice= invoiceTable.getModel().getValueAt(invoiceTable.getSelectedRow(), 1).toString();
        String itemName= invoiceTable.getModel().getValueAt(invoiceTable.getSelectedRow(), 2).toString();
        String companyName= companyCmbx.getSelectedItem().toString();
        
        try {
            if(InvoiceItemTable.delete(InputHelper.getIntegerInput(invoice), itemName,companyName)){
                invoiceTable.setModel(InvoiceItemTable.getInvoiceDetailsToTable(InputHelper.getIntegerInput(invoice)));
                totalAmountTxb.setText(Float.toString(InvoiceItemTable.getBill(InputHelper.getIntegerInput(invoiceNoTxb.getText()))));
            } else {
                JOptionPane.showMessageDialog(null, "Can't delete the row", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void itemNameCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameCmbxActionPerformed
        
    }//GEN-LAST:event_itemNameCmbxActionPerformed

    
    private void itemNameCmbxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemNameCmbxMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_itemNameCmbxMouseClicked

    private void itemNameCmbxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameCmbxKeyPressed
      
    
    }//GEN-LAST:event_itemNameCmbxKeyPressed

    private void itemNameCmbxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNameCmbxKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itemNameCmbxKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Payments p = new Payments("invoice",Integer.parseInt(invoiceNoTxb.getText()));
        p.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed
ArrayList keywords;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddInvoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddInvoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addCompanyBtn;
    private javax.swing.JButton addItemBtn;
    private javax.swing.JComboBox companyCmbx;
    private ch.rakudave.suggest.matcher.ContainsMatcher containsMatcher1;
    private javax.swing.JButton createInvoiceBtn;
    private datechooser.beans.DateChooserCombo dateDtp;
    private javax.swing.JTextField invoiceNoTxb;
    private javax.swing.JTable invoiceTable;
    private javax.swing.JComboBox itemNameCmbx;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newInvoiceBtn;
    private javax.swing.JTextField quantityTxb;
    private javax.swing.JLabel totalAmountTxb;
    // End of variables declaration//GEN-END:variables
}
