/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import inventorysystem.Beans.Company;
import inventorysystem.Beans.InvoiceItem;
import inventorysystem.Beans.Item;
import inventorysystem.Beans.VehicalInventory;
import inventorysystem.DB.DBType;
import inventorysystem.DB.DBUtil;
import inventorysystem.Tables.CompanyTable;
import inventorysystem.Tables.InvoiceItemTable;
import inventorysystem.Tables.ItemTable;
import inventorysystem.Tables.VehicalInventoryTable;
import inventorysystem.Tables.VehicalTable;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

/**
 *
 * @author srole_000
 */
public class AddItem extends javax.swing.JFrame {

    /**
     * Creates new form AddItem
     */
    public AddItem() {
        initComponents();
        nameCmbx.setVisible(false);
        nameCoboLbl.setVisible(false);
        //csTxb.setEditable(false);
        msgLbl.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        insetBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        msgLbl = new javax.swing.JLabel();
        newChbx = new javax.swing.JCheckBox();
        nameCmbx = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        apppTxb = new javax.swing.JTextField();
        wspppTxb = new javax.swing.JTextField();
        rpppTxb = new javax.swing.JTextField();
        appuTxb = new javax.swing.JTextField();
        wsppuTxb = new javax.swing.JTextField();
        rppuTxb = new javax.swing.JTextField();
        upbTxb = new javax.swing.JTextField();
        nameTxb = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namelbl = new javax.swing.JLabel();
        nameCoboLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add an Item");

        insetBtn.setText("Insert");
        insetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insetBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        msgLbl.setText("jLabel10");

        newChbx.setText("Not New Item");
        newChbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newChbxActionPerformed(evt);
            }
        });

        nameCmbx.setEditable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Item Details"));

        jLabel2.setText("Agent Price per pack");

        jLabel3.setText("W/S price per pack");

        jLabel4.setText("retail Price per pack");

        jLabel6.setText("W/S price per unit");

        jLabel7.setText("Retail price per unit");

        jLabel8.setText("Unit per box");

        jLabel5.setText("Agent price per unit");

        namelbl.setText("Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(namelbl)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upbTxb, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(rppuTxb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wsppuTxb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(appuTxb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rpppTxb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wspppTxb, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameTxb)
                    .addComponent(apppTxb))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(apppTxb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wspppTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rpppTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appuTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(wsppuTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(rppuTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(upbTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        nameCoboLbl.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(358, 358, 358)
                                .addComponent(insetBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameCoboLbl)
                                .addGap(18, 18, 18)
                                .addComponent(nameCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(newChbx))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(msgLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(newChbx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameCoboLbl))
                        .addGap(246, 246, 246))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insetBtn)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(msgLbl)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void insetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insetBtnActionPerformed
        // TODO add your handling code here:
        Item i = new Item(); // create an item
        i.setName(nameTxb.getText());
        i.setAgentPrice_pack(InputHelper.getPositiveFloat(apppTxb.getText()));
        i.setWsPrice_pack(InputHelper.getPositiveFloat(wspppTxb.getText()));
        i.setRetailPrice_pack(InputHelper.getPositiveFloat(rpppTxb.getText()));
        i.setAgentPrice_unit(InputHelper.getPositiveFloat(appuTxb.getText()));
        i.setWsPrice_unit(InputHelper.getPositiveFloat(wsppuTxb.getText()));
        i.setRetailPrice_unit(InputHelper.getPositiveFloat(rppuTxb.getText()));
        i.setUnitPerBox(InputHelper.getIntegerInput(upbTxb.getText()));

        String csql = "SELECT * FROM company";
        String vsql = "SELECT * FROM vehical";

        try (
                Connection conn = DBUtil.getConnection(DBType.MYSQL);
                Statement vstmt = conn.createStatement();
                ResultSet vrs = vstmt.executeQuery(vsql);) {
            //i.setCurrentStock(InputHelper.getIntegerInput(csTxb.getName()));
            if (!newChbx.isSelected()) { // if insert a new item
                if (ItemTable.insert(i)) { // first inset to the item table
                    // add default invoce
                    InvoiceItem ii = new InvoiceItem();
                    ii.setNoOfBox(0);
                    ii.setAgentPrice_pack(0);
                    ii.setWsPrice_pack(0);
                    ii.setRtailPrice_pack(0);
                    ii.setRemainingCapacity(0);
                    ii.setTotal(0);
                    ii.setStockId(0);
                    ii.setInvoiceNo(-1);
                    ii.setItemName(i.getName());

                    VehicalInventory vi = new VehicalInventory(); // vehicle inventory object
                    vi.setItemName(i.getName());
                    vi.setQuantityUnit(0);

                    // inserting to vehicle inventory
                    while (vrs.next()) {
                        vi.setVehicalName(vrs.getString("vehicalName"));

                        Statement cstmt = conn.createStatement();
                        ResultSet crs = cstmt.executeQuery(csql);
                        while (crs.next()) {
                            vi.setCompanyName(crs.getString("name"));
                            if (VehicalInventoryTable.insert(vi)) { // inserting to vehicle inventory
                                msgLbl.setText("Item Inserted correctly");
                            } else {
                                msgLbl.setText("Default invoice wan't Inserted correctly");
                            }
                        }
                    }

                    // inserting default invoice 
                    Statement cstmt = conn.createStatement();
                    ResultSet crs = cstmt.executeQuery(csql);
                    while (crs.next()) {

                        ii.setCompanyName(crs.getString("name"));
                        if (InvoiceItemTable.insert(ii)) { //inserting default invoice
                            msgLbl.setText("Item Inserted correctly");
                        } else {
                            msgLbl.setText("Default invoice wan't Inserted correctly");
                        }
                    }

                }
            } else { // if update
                if (ItemTable.update(i)) {
                    msgLbl.setText("Updated correctly");
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_insetBtnActionPerformed

    private void newChbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newChbxActionPerformed
        // TODO add your handling code here:
        if (newChbx.isSelected()) {
            nameTxb.setVisible(false);
            namelbl.setVisible(false);
            nameCmbx.setVisible(true);
            nameCoboLbl.setVisible(true);
            insetBtn.setText("Update");

            // event
            nameCmbx.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
                @Override
                public void keyReleased(KeyEvent evt) {
                    String str = nameCmbx.getEditor().getItem().toString();

                    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                        try {
                            Item i = ItemTable.getRow(nameCmbx.getSelectedItem().toString());
                            apppTxb.setText(Float.toString(i.getAgentPrice_pack()));
                            wspppTxb.setText(Float.toString(i.getWsPrice_pack()));
                            rpppTxb.setText(Float.toString(i.getRetailPrice_pack()));
                            appuTxb.setText(Float.toString(i.getAgentPrice_unit()));
                            wsppuTxb.setText(Float.toString(i.getWsPrice_unit()));
                            rppuTxb.setText(Float.toString(i.getRetailPrice_unit()));
                            upbTxb.setText(Integer.toString(i.getUnitPerBox()));

                        } catch (SQLException ex) {
                            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    }

                    if (evt.getKeyCode() >= 65 && evt.getKeyCode() <= 90 || evt.getKeyCode() >= 96 && evt.getKeyCode() <= 105 || evt.getKeyCode() == 8) {
                        try {
                            nameCmbx.setModel(ItemTable.getList(str));
                            if (nameCmbx.getItemCount() > 0) {
                                nameCmbx.showPopup();
                                if (evt.getKeyCode() != 8) {
                                    ((JTextComponent) nameCmbx.getEditor().getEditorComponent()).select(str.length(), nameCmbx.getEditor().getItem().toString().length());
                                } else {
                                    nameCmbx.getEditor().setItem(str);
                                }
                            } else {
                                nameCmbx.getEditor().setItem(str);
                            }
                        } catch (SQLException ex) {
                            Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                }
            });

        } else {
            nameTxb.setVisible(true);
            namelbl.setVisible(true);
            nameCmbx.setVisible(false);
            nameCoboLbl.setVisible(false);
            insetBtn.setText("Insert");
        }
    }//GEN-LAST:event_newChbxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apppTxb;
    private javax.swing.JTextField appuTxb;
    private javax.swing.JButton insetBtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel msgLbl;
    private javax.swing.JComboBox nameCmbx;
    private javax.swing.JLabel nameCoboLbl;
    private javax.swing.JTextField nameTxb;
    private javax.swing.JLabel namelbl;
    private javax.swing.JCheckBox newChbx;
    private javax.swing.JTextField rpppTxb;
    private javax.swing.JTextField rppuTxb;
    private javax.swing.JTextField upbTxb;
    private javax.swing.JTextField wspppTxb;
    private javax.swing.JTextField wsppuTxb;
    // End of variables declaration//GEN-END:variables
}
