/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorysystem;

import inventorysystem.Beans.Cheque;
import inventorysystem.Beans.InvoiceItem;
import inventorysystem.Beans.Payment;
import inventorysystem.Beans.PaymentInvoice;
import inventorysystem.Tables.BillItemTable;
import inventorysystem.Tables.ChequeTable;
import inventorysystem.Tables.DiscountTable;
import inventorysystem.Tables.InvoiceItemTable;
import inventorysystem.Tables.PaymentInvoiceTable;
import inventorysystem.Tables.PaymentTable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author srole_000
 */
public class Payments extends javax.swing.JFrame {

    /**
     * Creates new form Payments
     */
    String cat = "";
    int no = 0;

    
    
    public Payments(String cat, int no) {
        initComponents();
        this.cat = cat;
        this.no = no;

        // enable/disables
        paymentCatCmbx.setEnabled(false);
        statusTxb.setEnabled(false);
        chequePanel.setVisible(false);
        //auto selections
        creditRbtn.setSelected(true);

        if (cat.equalsIgnoreCase("Bill")) {// if it is bill
            invoiceBillNoLbl.setText("Bill No");
            billNoTxb.setText(Integer.toString(no));
            statusTxb.setText(creditRbtn.getText());
            inoutComeTxb.setText("Income");
            float bill = BillItemTable.getBill(no);
            float discount = DiscountTable.getDiscountForBill(no);
            billAmountTbx.setText(Float.toString(bill));
            discountTbx.setText(Float.toString(discount));

            totalAmountTxb.setText(Float.toString(bill - discount));

            //shopAgentTxb.setText("Pay by Shop");
        } else if (cat.equalsIgnoreCase("invoice")) { // if it is invoice
            invoiceBillNoLbl.setText("Invoice No");
            billNoTxb.setText(Integer.toString(no));
            statusTxb.setText(creditRbtn.getText());
            inoutComeTxb.setText("Outgoing");
            float bill = InvoiceItemTable.getBill(no);
            billAmountTbx.setText(Float.toString(bill));
            discountTbx.setText(Integer.toString(0));
            totalAmountTxb.setText(Float.toString(bill));
            //shopAgentTxb.setText("Pay by Shop");
        }
    }

    public Payments() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        creditRbtn = new javax.swing.JRadioButton();
        chequeRbtn = new javax.swing.JRadioButton();
        cashRbtn = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        paymentCatCmbx = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        billNoTxb = new javax.swing.JTextField();
        invoiceBillNoLbl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        statusTxb = new javax.swing.JTextField();
        inoutComeTxb = new javax.swing.JTextField();
        totalAmountTxb = new javax.swing.JTextField();
        paidAmountTxb = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        balanceTxb = new javax.swing.JTextField();
        chequePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chequeNoTbx = new javax.swing.JTextField();
        bankTbx = new javax.swing.JTextField();
        chequeDateDtp = new datechooser.beans.DateChooserCombo();
        amountTbx = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTbl = new javax.swing.JTable();
        dateDtp = new datechooser.beans.DateChooserCombo();
        msgLbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        billAmountTbx = new javax.swing.JTextField();
        discountTbx = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Payments");

        buttonGroup2.add(creditRbtn);
        creditRbtn.setText("Credit");
        creditRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditRbtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(chequeRbtn);
        chequeRbtn.setText("Cheque");
        chequeRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chequeRbtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(cashRbtn);
        cashRbtn.setText("Cash");
        cashRbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cashRbtn)
                    .addComponent(chequeRbtn)
                    .addComponent(creditRbtn))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(creditRbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chequeRbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cashRbtn)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jLabel1.setText("Find payamet");

        paymentCatCmbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "By Shop", "To Agent" }));

        jCheckBox1.setText("Change shop/agent");

        billNoTxb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                billNoTxbFocusLost(evt);
            }
        });
        billNoTxb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billNoTxbActionPerformed(evt);
            }
        });

        invoiceBillNoLbl.setText("Invoice/Bill No");

        jLabel4.setText("Status");

        jLabel5.setText("In/Out Come");

        jLabel6.setText("Total Amount");

        jLabel7.setText("paid Amount");

        jLabel8.setText("Shop/Agent");

        paidAmountTxb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                paidAmountTxbFocusLost(evt);
            }
        });
        paidAmountTxb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paidAmountTxbKeyPressed(evt);
            }
        });

        jButton1.setText("Pay");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Balance");

        jLabel3.setText("Add Chequ Details");

        jLabel9.setText("Cheque No");

        jLabel10.setText("Bank");

        jLabel11.setText("Ex: Date");

        jLabel12.setText("Amount");

        chequeDateDtp.setCalendarPreferredSize(new java.awt.Dimension(350, 280));

        javax.swing.GroupLayout chequePanelLayout = new javax.swing.GroupLayout(chequePanel);
        chequePanel.setLayout(chequePanelLayout);
        chequePanelLayout.setHorizontalGroup(
            chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chequePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(chequePanelLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(chequePanelLayout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel3))
                                .addGroup(chequePanelLayout.createSequentialGroup()
                                    .addGap(16, 16, 16)
                                    .addComponent(chequeNoTbx, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(chequePanelLayout.createSequentialGroup()
                            .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addGap(27, 27, 27)
                            .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bankTbx)
                                .addComponent(chequeDateDtp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(amountTbx, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        chequePanelLayout.setVerticalGroup(
            chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chequePanelLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(chequeNoTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(bankTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(chequeDateDtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(chequePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(amountTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
        );

        paymentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(paymentTbl);

        dateDtp.setCalendarPreferredSize(new java.awt.Dimension(350, 280));
        dateDtp.setFormat(2);

        msgLbl.setText("Message");

        jLabel13.setText("Bill Amount");

        jLabel14.setText("Discount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(invoiceBillNoLbl)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balanceTxb)
                            .addComponent(paidAmountTxb)
                            .addComponent(totalAmountTxb)
                            .addComponent(inoutComeTxb)
                            .addComponent(statusTxb)
                            .addComponent(billNoTxb)
                            .addComponent(paymentCatCmbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(billAmountTbx)
                            .addComponent(discountTbx)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(msgLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(chequePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateDtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(dateDtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chequePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentCatCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(billNoTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceBillNoLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(statusTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inoutComeTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(billAmountTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(discountTbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(totalAmountTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(paidAmountTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(balanceTxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(msgLbl))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditRbtnActionPerformed
        // TODO add your handling code here:
        //cat="Bill";
        chequePanel.setVisible(false);
        if (cat.equalsIgnoreCase("Bill")) {
            invoiceBillNoLbl.setText("Bill No");
            billNoTxb.setText(Integer.toString(no));
            statusTxb.setText("Credit");
            inoutComeTxb.setText("Income");
            totalAmountTxb.setText(Float.toString(BillItemTable.getIssuedBill(InputHelper.getIntegerInput(billNoTxb.getText()))));
            //shopAgentTxb.setText("Pay by Shop");
        }
    }//GEN-LAST:event_creditRbtnActionPerformed

    private void chequeRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chequeRbtnActionPerformed
        // TODO add your handling code here:
        //cat="Cheque";

        chequePanel.setVisible(false);
        if (cat.equalsIgnoreCase("Bill")) {
            invoiceBillNoLbl.setText("Bill No");
            billNoTxb.setText(Integer.toString(no));
            statusTxb.setText("Pending");
            inoutComeTxb.setText("Income");
            totalAmountTxb.setText(Float.toString(BillItemTable.getIssuedBill(InputHelper.getIntegerInput(billNoTxb.getText()))));
            //shopAgentTxb.setText("Pay by Shop");
        }

        chequePanel.setVisible(true);

    }//GEN-LAST:event_chequeRbtnActionPerformed

    private void cashRbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRbtnActionPerformed
        // TODO add your handling code here:

        if (cat.equalsIgnoreCase("Bill")) {
            invoiceBillNoLbl.setText("Bill No");
            billNoTxb.setText(Integer.toString(no));
            statusTxb.setText("Paid");
            inoutComeTxb.setText("Income");
            totalAmountTxb.setText(Float.toString(BillItemTable.getIssuedBill(InputHelper.getIntegerInput(billNoTxb.getText()))));
            //shopAgentTxb.setText("Pay by Shop");
        }
        chequePanel.setVisible(false);
        chequePanel.setVisible(false);
    }//GEN-LAST:event_cashRbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Payment p = new Payment();
        p.setBillNo(InputHelper.getIntegerInput(billNoTxb.getText()));
        p.setPaymentType(creditRbtn.getText());

        p.setPaidDate(InputHelper.getValidFormatedDate(dateDtp.getText()));

        p.setTotalAmount(InputHelper.getPositiveFloat(totalAmountTxb.getText()));
        p.setPaidAmount(InputHelper.getPositiveFloat(paidAmountTxb.getText()));

        if (cat.equalsIgnoreCase("Bill")) { // if it is billing

            p.setInout(inoutComeTxb.getText());

        } else if (cat.equalsIgnoreCase("invoice")) { // if it is invoice
            p.setInout(inoutComeTxb.getText());

        }

        if (creditRbtn.isSelected()) {// if this is credited

            p.setStatus("Credited");

            try {
                if (PaymentTable.insert(p)) { // update payment either way
                    msgLbl.setText("Payment is successfully updated");
                    if (cat.equalsIgnoreCase("invoice")) { // if it is invoice
                        PaymentInvoice pi = new PaymentInvoice();
                        pi.setInvoiceId(p.getBillNo());
                        pi.setPaymentId(p.getPaymentId());
                        if (PaymentInvoiceTable.insert(pi)) {
                            msgLbl.setText("payment sucessfully placed");
                        }
                    }
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Can't insert payment data", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else if (chequeRbtn.isSelected()) {// if this is a cheque
            p.setStatus("Cheque");

            try {
                if (PaymentTable.insert(p)) { // update payment either way
                    msgLbl.setText("Payment is successfully updated");
                    if (cat.equalsIgnoreCase("invoice")) { // if it is invoice
                        PaymentInvoice pi = new PaymentInvoice();
                        pi.setInvoiceId(p.getBillNo());
                        pi.setPaymentId(p.getPaymentId());
                        if (PaymentInvoiceTable.insert(pi)) {
                            msgLbl.setText("payment sucessfully placed");
                        }
                    }

                    // place cheque details
                    Cheque c = new Cheque();
                    c.setChequeNo(Integer.parseInt(chequeNoTbx.getText()));
                    c.setBank(bankTbx.getText());
                    c.setExDate(InputHelper.getValidFormatedDate(chequeDateDtp.getText().toString()));
                    c.setAmount(Float.parseFloat(amountTbx.getText()));
                    c.setPaymentId(p.getPaymentId());

                    if (ChequeTable.insert(c)) {
                        msgLbl.setText("payment + cheque sucessfully placed");
                    }

                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Can't insert payment data", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else if (cashRbtn.isSelected()) {//if this is a cash amount
            p.setStatus("Cash");

            try {
                if (PaymentTable.insert(p)) { // update payment either way
                    msgLbl.setText("Payment is successfully updated");
                    if (cat.equalsIgnoreCase("invoice")) { // if it is invoice
                        PaymentInvoice pi = new PaymentInvoice();
                        pi.setInvoiceId(p.getBillNo());
                        pi.setPaymentId(p.getPaymentId());
                        if (PaymentInvoiceTable.insert(pi)) {
                            msgLbl.setText("payment sucessfully placed");
                        }
                    }
                }

            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Can't insert payment data", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void billNoTxbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billNoTxbActionPerformed
        // TODO add your handling code here:
        totalAmountTxb.setText(Float.toString(BillItemTable.getIssuedBill(InputHelper.getIntegerInput(billNoTxb.getText()))));
    }//GEN-LAST:event_billNoTxbActionPerformed

    private void billNoTxbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_billNoTxbFocusLost
        // TODO add your handling code here:
        totalAmountTxb.setText(Float.toString(BillItemTable.getIssuedBill(InputHelper.getIntegerInput(billNoTxb.getText()))));
    }//GEN-LAST:event_billNoTxbFocusLost

    private void paidAmountTxbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paidAmountTxbKeyPressed
        // TODO add your handling code here:

        // balanceTxb.setText(Integer.toString(InputHelper.getIntegerInput(totalAmountTxb.getText())-InputHelper.getIntegerInput(paidAmountTxb.getText())));
    }//GEN-LAST:event_paidAmountTxbKeyPressed

    private void paidAmountTxbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paidAmountTxbFocusLost
        // TODO add your handling code here:
        balanceTxb.setText(Float.toString(InputHelper.getPositiveFloat(paidAmountTxb.getText().trim()) - InputHelper.getPositiveFloat(totalAmountTxb.getText().trim())));
    }//GEN-LAST:event_paidAmountTxbFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payments().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountTbx;
    private javax.swing.JTextField balanceTxb;
    private javax.swing.JTextField bankTbx;
    private javax.swing.JTextField billAmountTbx;
    private javax.swing.JTextField billNoTxb;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton cashRbtn;
    private datechooser.beans.DateChooserCombo chequeDateDtp;
    private javax.swing.JTextField chequeNoTbx;
    private javax.swing.JPanel chequePanel;
    private javax.swing.JRadioButton chequeRbtn;
    private javax.swing.JRadioButton creditRbtn;
    private datechooser.beans.DateChooserCombo dateDtp;
    private javax.swing.JTextField discountTbx;
    private javax.swing.JTextField inoutComeTxb;
    private javax.swing.JLabel invoiceBillNoLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel msgLbl;
    private javax.swing.JTextField paidAmountTxb;
    private javax.swing.JComboBox paymentCatCmbx;
    private javax.swing.JTable paymentTbl;
    private javax.swing.JTextField statusTxb;
    private javax.swing.JTextField totalAmountTxb;
    // End of variables declaration//GEN-END:variables
}
